[tool.isort]
profile = "black"
line_length = 88
src_paths = ["src", "tests", "utils", "notebooks"]
known_first_party = ["app", "ui", "utils", "notebooks"]
include_trailing_comma = true
force_sort_within_sections = true
combine_as_imports = true
lines_after_imports = 2
